name: Build and push docker automysqlbackup image
on:
  push:
    tags:
      - v*
    branches:    
      - '**'

  workflow_dispatch:

concurrency: 
  group: image-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and push docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/averni/automysqlbackup
            docker.io/averni/automysqlbackup
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=raw,value=latest

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          cache-from: type=registry,ref=ghcr.io/averni/automysqlbackup:buildcache
          cache-to: type=registry,ref=ghcr.io/averni/automysqlbackup:buildcache,mode=max
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
